# Generated by Django 5.0.2 on 2024-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(max_length=150, verbose_name='ссылка'),
        ),
    ]
