# Generated by Django 5.0.2 on 2024-03-15 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('payment_date',), 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 21, 10, 16, 161152, tzinfo=datetime.timezone.utc), verbose_name='дата оплаты'),
        ),
    ]
