# Generated by Django 5.0.2 on 2024-03-22 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 24, 40, 324963, tzinfo=datetime.timezone.utc), verbose_name='дата оплаты'),
        ),
    ]
