# Generated by Django 5.0.2 on 2024-03-15 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_payment_options_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='lms/static/images', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 21, 31, 58, 546263, tzinfo=datetime.timezone.utc), verbose_name='дата оплаты'),
        ),
    ]
